fix pagination issue for large number of pages
Docushield/MintIt-Front pull request #239
Opened 2022-12-15 11:31 UTC by mubashir-tnm

2022-12-19 04:42 UTC, abdur-docushield requested changes

2022-12-19 04:42 UTC, abdur-docushield commented on src/containers/author-profile/layout-02/index.jsx
> +    const POSTS_PER_PAGE = 21;
Why 21?

2022-12-19 04:44 UTC, mubashir-tnm commented on src/containers/author-profile/layout-02/index.jsx
> +    const POSTS_PER_PAGE = 21;
because there are 3 items per row,
21/3 = 7 rows

2023-01-05 09:12 UTC, abdur-docushield approved these changes

2023-01-05 10:16 UTC, merged